# Generated by Django 4.1.3 on 2022-11-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='CounterUserModel',
        ),
    ]
